### PR TITLE
Auto-formatting

### PR DESCRIPTION
**Pull request by sandstrom**
Excel shows a warning if numeric strings (strings with only numeric characters) are present in a spreadsheet. While this can be handled on the ruby-side it's convenient to solve this within the library.

screen shot 2017-09-07 at 16 56 51

***

@felixbuenemann Let me know what you think! Also, I've added a version-bump. But we can skip that if you want, your choice!

Closes https://github.com/felixbuenemann/xlsxtream/issues/7

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Thanks!

From reading the commits this looks fine. I haven't yet had time to test it out manually.

I'm not too happy about all the whitespace and formatting changes, because it makes it very hard to see the actual changes introduced, but I don't think it's worth the effort of reverting them.

I recommend keeping changes to what's actually required for the feature or fix when contributing to a library in the future. It makes it easier for maintainers to review and merge changes and keeps the commit history healthy.

Thanks for adding a Changelog, could you amend the commit to use the full version number? (0.1.0, …)

**Comment by sandstrom** [comment]
Happy to hear!

I agree on keeping changes to the minimum, sometimes I add whitespace out of habit (in our projects we use whitespace quite liberally, but I understand that people have different views on this).

I've updated the changelog.

**Comment by felixbuenemann** [comment]
@sandstrom I just noticed, that you set `spec.required_ruby_version = '>= 2.0'` in the gemspec.

Is there a particular reason for the requirement? You are using the `Encoding` class, but it has been present since ruby 1.9.

**Comment by sandstrom** [comment]
@felixbuenemann Yes, I wanted to discuss that with you. I don't have ruby below 2.0 so I cannot test it. And it seems like a reasonable minimum, few are using ruby below 2.0 these days[1].

If you want to we can drop that change.

**Comment by felixbuenemann** [comment]
No need to drop it, just set it to `>= 1.9.1`. I'll verify it before merging.

**Comment by sandstrom** [comment]
@felixbuenemann I've updated it. Is there anything else you want me to change?

**Comment by felixbuenemann** [comment]
No, I think that's all.

**Comment by felixbuenemann** [comment]
@sandstrom I've released 0.3.0, thanks for your contribution!

**Comment by sandstrom** [comment]
@felixbuenemann Thanks for working with me on this! 🏅

**Pull request merged**
